NAME = avutil
DESC = FFmpeg utility library

HEADERS = adler32.h                                                     \
          aes.h                                                         \
          aes_ctr.h                                                     \
          ambient_viewing_environment.h                                 \
          attributes.h                                                  \
          audio_fifo.h                                                  \
          avassert.h                                                    \
          avstring.h                                                    \
          avutil.h                                                      \
          base64.h                                                      \
          blowfish.h                                                    \
          bprint.h                                                      \
          bswap.h                                                       \
          buffer.h                                                      \
          cast5.h                                                       \
          camellia.h                                                    \
          channel_layout.h                                              \
          common.h                                                      \
          cpu.h                                                         \
          crc.h                                                         \
          csp.h                                                         \
          des.h                                                         \
          detection_bbox.h                                              \
          dict.h                                                        \
          display.h                                                     \
          dovi_meta.h                                                   \
          downmix_info.h                                                \
          encryption_info.h                                             \
          error.h                                                       \
          eval.h                                                        \
          executor.h                                                    \
          fifo.h                                                        \
          file.h                                                        \
          frame.h                                                       \
          hash.h                                                        \
          hdr_dynamic_metadata.h                                        \
          hdr_dynamic_vivid_metadata.h                                  \
          hmac.h                                                        \
          hwcontext.h                                                   \
          hwcontext_cuda.h                                              \
          hwcontext_d3d11va.h                                           \
          hwcontext_d3d12va.h                                           \
          hwcontext_drm.h                                               \
          hwcontext_dxva2.h                                             \
          hwcontext_qsv.h                                               \
          hwcontext_mediacodec.h                                        \
          hwcontext_opencl.h                                            \
          hwcontext_vaapi.h                                             \
          hwcontext_videotoolbox.h                                      \
          hwcontext_vdpau.h                                             \
          hwcontext_vulkan.h                                            \
          iamf.h                                                        \
          imgutils.h                                                    \
          intfloat.h                                                    \
          intreadwrite.h                                                \
          json.h                                                        \
          lfg.h                                                         \
          log.h                                                         \
          lzo.h                                                         \
          macros.h                                                      \
          mathematics.h                                                 \
          mastering_display_metadata.h                                  \
          md5.h                                                         \
          mem.h                                                         \
          motion_vector.h                                               \
          murmur3.h                                                     \
          opt.h                                                         \
          parseutils.h                                                  \
          pixdesc.h                                                     \
          pixelutils.h                                                  \
          pixfmt.h                                                      \
          random_seed.h                                                 \
          rc4.h                                                         \
          rational.h                                                    \
          replaygain.h                                                  \
          ripemd.h                                                      \
          samplefmt.h                                                   \
          sha.h                                                         \
          sha512.h                                                      \
          spherical.h                                                   \
          stereo3d.h                                                    \
          threadmessage.h                                               \
          time.h                                                        \
          timecode.h                                                    \
          timestamp.h                                                   \
          tree.h                                                        \
          twofish.h                                                     \
          uuid.h                                                        \
          version.h                                                     \
          video_enc_params.h                                            \
          xtea.h                                                        \
          tea.h                                                         \
          tx.h                                                          \
          film_grain_params.h                                           \
          video_hint.h

ARCH_HEADERS = bswap.h                                                  \
               intmath.h                                                \
               intreadwrite.h                                           \
               timer.h                                                  \

BUILT_HEADERS = avconfig.h                                              \
                ffversion.h

OBJS = adler32.o                                                        \
       aes.o                                                            \
       aes_ctr.o                                                        \
       ambient_viewing_environment.o                                    \
       audio_fifo.o                                                     \
       avstring.o                                                       \
       avsscanf.o                                                       \
       base64.o                                                         \
       blowfish.o                                                       \
       bprint.o                                                         \
       buffer.o                                                         \
       cast5.o                                                          \
       camellia.o                                                       \
       channel_layout.o                                                 \
       cpu.o                                                            \
       crc.o                                                            \
       csp.o                                                            \
       des.o                                                            \
       detection_bbox.o                                                 \
       dict.o                                                           \
       display.o                                                        \
       dovi_meta.o                                                      \
       downmix_info.o                                                   \
       encryption_info.o                                                \
       error.o                                                          \
       eval.o                                                           \
       executor.o                                                       \
       fifo.o                                                           \
       file.o                                                           \
       file_open.o                                                      \
       float_dsp.o                                                      \
       fixed_dsp.o                                                      \
       frame.o                                                          \
       hash.o                                                           \
       hdr_dynamic_metadata.o                                           \
       hdr_dynamic_vivid_metadata.o                                     \
       hmac.o                                                           \
       hwcontext.o                                                      \
       iamf.o                                                           \
       imgutils.o                                                       \
       integer.o                                                        \
       intmath.o                                                        \
       json.o                                                           \
       json_dump.o                                                      \
       json_parse.o                                                     \
       lfg.o                                                            \
       lls.o                                                            \
       log.o                                                            \
       log2_tab.o                                                       \
       lzo.o                                                            \
       mathematics.o                                                    \
       mastering_display_metadata.o                                     \
       md5.o                                                            \
       mem.o                                                            \
       murmur3.o                                                        \
       opt.o                                                            \
       parseutils.o                                                     \
       pixdesc.o                                                        \
       pixelutils.o                                                     \
       random_seed.o                                                    \
       rational.o                                                       \
       reverse.o                                                        \
       rc4.o                                                            \
       ripemd.o                                                         \
       samplefmt.o                                                      \
       sha.o                                                            \
       sha512.o                                                         \
       slicethread.o                                                    \
       spherical.o                                                      \
       stereo3d.o                                                       \
       threadmessage.o                                                  \
       time.o                                                           \
       timecode.o                                                       \
       timestamp.o                                                      \
       tree.o                                                           \
       twofish.o                                                        \
       utils.o                                                          \
       xga_font_data.o                                                  \
       xtea.o                                                           \
       tea.o                                                            \
       tx.o                                                             \
       tx_float.o                                                       \
       tx_double.o                                                      \
       tx_int32.o                                                       \
       uuid.o                                                           \
       version.o                                                        \
       video_enc_params.o                                               \
       video_hint.o                                                     \
       film_grain_params.o                                              \
       script_python.o                                                  \
       script_quickjs.o                                                 \
       script.o                                                         \


OBJS-$(CONFIG_CUDA)                     += hwcontext_cuda.o
OBJS-$(CONFIG_D3D11VA)                  += hwcontext_d3d11va.o
OBJS-$(CONFIG_D3D12VA)                  += hwcontext_d3d12va.o
OBJS-$(CONFIG_DXVA2)                    += hwcontext_dxva2.o
OBJS-$(CONFIG_LIBDRM)                   += hwcontext_drm.o
OBJS-$(CONFIG_MACOS_KPERF)              += macos_kperf.o
OBJS-$(CONFIG_MEDIACODEC)               += hwcontext_mediacodec.o
OBJS-$(CONFIG_OPENCL)                   += hwcontext_opencl.o
OBJS-$(CONFIG_QSV)                      += hwcontext_qsv.o
OBJS-$(CONFIG_VAAPI)                    += hwcontext_vaapi.o
OBJS-$(CONFIG_VIDEOTOOLBOX)             += hwcontext_videotoolbox.o
OBJS-$(CONFIG_VDPAU)                    += hwcontext_vdpau.o
OBJS-$(CONFIG_VULKAN)                   += hwcontext_vulkan.o vulkan.o

OBJS-$(!CONFIG_VULKAN)                  += hwcontext_stub.o

OBJS += $(COMPAT_OBJS:%=../compat/%)

# zeromq
ZEROMQ_OBJS += zeromq/external/sha1/sha1.o
ZEROMQ_OBJS += zeromq/src/address.o
ZEROMQ_OBJS += zeromq/src/channel.o
ZEROMQ_OBJS += zeromq/src/client.o
ZEROMQ_OBJS += zeromq/src/clock.o
ZEROMQ_OBJS += zeromq/src/ctx.o
ZEROMQ_OBJS += zeromq/src/curve_client.o
ZEROMQ_OBJS += zeromq/src/curve_mechanism_base.o
ZEROMQ_OBJS += zeromq/src/curve_server.o
ZEROMQ_OBJS += zeromq/src/dealer.o
ZEROMQ_OBJS += zeromq/src/decoder_allocators.o
ZEROMQ_OBJS += zeromq/src/devpoll.o
ZEROMQ_OBJS += zeromq/src/dgram.o
ZEROMQ_OBJS += zeromq/src/dish.o
ZEROMQ_OBJS += zeromq/src/dist.o
ZEROMQ_OBJS += zeromq/src/endpoint.o
ZEROMQ_OBJS += zeromq/src/epoll.o
ZEROMQ_OBJS += zeromq/src/err.o
ZEROMQ_OBJS += zeromq/src/fq.o
ZEROMQ_OBJS += zeromq/src/gather.o
ZEROMQ_OBJS += zeromq/src/gssapi_client.o
ZEROMQ_OBJS += zeromq/src/gssapi_mechanism_base.o
ZEROMQ_OBJS += zeromq/src/gssapi_server.o
ZEROMQ_OBJS += zeromq/src/io_object.o
ZEROMQ_OBJS += zeromq/src/io_thread.o
ZEROMQ_OBJS += zeromq/src/ip.o
ZEROMQ_OBJS += zeromq/src/ip_resolver.o
ZEROMQ_OBJS += zeromq/src/ipc_address.o
ZEROMQ_OBJS += zeromq/src/ipc_connecter.o
ZEROMQ_OBJS += zeromq/src/ipc_listener.o
ZEROMQ_OBJS += zeromq/src/kqueue.o
ZEROMQ_OBJS += zeromq/src/lb.o
ZEROMQ_OBJS += zeromq/src/mailbox.o
ZEROMQ_OBJS += zeromq/src/mailbox_safe.o
ZEROMQ_OBJS += zeromq/src/mechanism.o
ZEROMQ_OBJS += zeromq/src/mechanism_base.o
ZEROMQ_OBJS += zeromq/src/metadata.o
ZEROMQ_OBJS += zeromq/src/msg.o
ZEROMQ_OBJS += zeromq/src/mtrie.o
ZEROMQ_OBJS += zeromq/src/norm_engine.o
ZEROMQ_OBJS += zeromq/src/null_mechanism.o
ZEROMQ_OBJS += zeromq/src/object.o
ZEROMQ_OBJS += zeromq/src/options.o
ZEROMQ_OBJS += zeromq/src/own.o
ZEROMQ_OBJS += zeromq/src/pair.o
ZEROMQ_OBJS += zeromq/src/peer.o
ZEROMQ_OBJS += zeromq/src/pgm_receiver.o
ZEROMQ_OBJS += zeromq/src/pgm_sender.o
ZEROMQ_OBJS += zeromq/src/pgm_socket.o
ZEROMQ_OBJS += zeromq/src/pipe.o
ZEROMQ_OBJS += zeromq/src/plain_client.o
ZEROMQ_OBJS += zeromq/src/plain_server.o
ZEROMQ_OBJS += zeromq/src/poll.o
ZEROMQ_OBJS += zeromq/src/poller_base.o
ZEROMQ_OBJS += zeromq/src/polling_util.o
ZEROMQ_OBJS += zeromq/src/pollset.o
ZEROMQ_OBJS += zeromq/src/precompiled.o
ZEROMQ_OBJS += zeromq/src/proxy.o
ZEROMQ_OBJS += zeromq/src/pub.o
ZEROMQ_OBJS += zeromq/src/pull.o
ZEROMQ_OBJS += zeromq/src/push.o
ZEROMQ_OBJS += zeromq/src/radio.o
ZEROMQ_OBJS += zeromq/src/radix_tree.o
ZEROMQ_OBJS += zeromq/src/random.o
ZEROMQ_OBJS += zeromq/src/raw_decoder.o
ZEROMQ_OBJS += zeromq/src/raw_encoder.o
ZEROMQ_OBJS += zeromq/src/raw_engine.o
ZEROMQ_OBJS += zeromq/src/reaper.o
ZEROMQ_OBJS += zeromq/src/rep.o
ZEROMQ_OBJS += zeromq/src/req.o
ZEROMQ_OBJS += zeromq/src/router.o
ZEROMQ_OBJS += zeromq/src/scatter.o
ZEROMQ_OBJS += zeromq/src/select.o
ZEROMQ_OBJS += zeromq/src/server.o
ZEROMQ_OBJS += zeromq/src/session_base.o
ZEROMQ_OBJS += zeromq/src/signaler.o
ZEROMQ_OBJS += zeromq/src/socket_base.o
ZEROMQ_OBJS += zeromq/src/socket_poller.o
ZEROMQ_OBJS += zeromq/src/socks.o
ZEROMQ_OBJS += zeromq/src/socks_connecter.o
ZEROMQ_OBJS += zeromq/src/stream.o
ZEROMQ_OBJS += zeromq/src/stream_connecter_base.o
ZEROMQ_OBJS += zeromq/src/stream_engine_base.o
ZEROMQ_OBJS += zeromq/src/stream_listener_base.o
ZEROMQ_OBJS += zeromq/src/sub.o
ZEROMQ_OBJS += zeromq/src/tcp.o
ZEROMQ_OBJS += zeromq/src/tcp_address.o
ZEROMQ_OBJS += zeromq/src/tcp_connecter.o
ZEROMQ_OBJS += zeromq/src/tcp_listener.o
ZEROMQ_OBJS += zeromq/src/thread.o
ZEROMQ_OBJS += zeromq/src/timers.o
ZEROMQ_OBJS += zeromq/src/tipc_address.o
ZEROMQ_OBJS += zeromq/src/tipc_connecter.o
ZEROMQ_OBJS += zeromq/src/tipc_listener.o
ZEROMQ_OBJS += zeromq/src/trie.o
ZEROMQ_OBJS += zeromq/src/udp_address.o
ZEROMQ_OBJS += zeromq/src/udp_engine.o
ZEROMQ_OBJS += zeromq/src/v1_decoder.o
ZEROMQ_OBJS += zeromq/src/v1_encoder.o
ZEROMQ_OBJS += zeromq/src/v2_decoder.o
ZEROMQ_OBJS += zeromq/src/v2_encoder.o
ZEROMQ_OBJS += zeromq/src/v3_1_encoder.o
ZEROMQ_OBJS += zeromq/src/vmci.o
ZEROMQ_OBJS += zeromq/src/vmci_address.o
ZEROMQ_OBJS += zeromq/src/vmci_connecter.o
ZEROMQ_OBJS += zeromq/src/vmci_listener.o
ZEROMQ_OBJS += zeromq/src/ws_address.o
ZEROMQ_OBJS += zeromq/src/ws_connecter.o
ZEROMQ_OBJS += zeromq/src/ws_decoder.o
ZEROMQ_OBJS += zeromq/src/ws_encoder.o
ZEROMQ_OBJS += zeromq/src/ws_engine.o
ZEROMQ_OBJS += zeromq/src/ws_listener.o
ZEROMQ_OBJS += zeromq/src/wss_address.o
ZEROMQ_OBJS += zeromq/src/xpub.o
ZEROMQ_OBJS += zeromq/src/xsub.o
ZEROMQ_OBJS += zeromq/src/zap_client.o
ZEROMQ_OBJS += zeromq/src/zmq.o
ZEROMQ_OBJS += zeromq/src/zmq_utils.o
ZEROMQ_OBJS += zeromq/src/zmtp_engine.o
ZEROMQ_OBJS-$(CONFIG_WEPOLL) += zeromq/external/wepoll/wepoll.o
ZEROMQ_OBJS += $(ZEROMQ_OBJS-yes)

$(addprefix $(SUBDIR), $(ZEROMQ_OBJS)): CFLAGS += -I$(SUBDIR)zeromq/src

OBJS-$(CONFIG_LIBZMQ) += $(ZEROMQ_OBJS)

# rtmidi
RTMIDI_OBJS += rtmidi/RtMidi.o

$(SUBDIR)rtmidi/RtMidi.o: CXXFLAGS += -DRTMIDI_EXPORT $(RTMIDI_API)

OBJS-$(CONFIG_RTMIDI) += $(RTMIDI_OBJS)
OBJS-$(CONFIG_RTMIDI) += quickjs-rtmidi.o

# quickjs
QUICKJS_OBJS += quickjs/cutils.o
QUICKJS_OBJS += quickjs/libbf.o
QUICKJS_OBJS += quickjs/libregexp.o
QUICKJS_OBJS += quickjs/libunicode.o
QUICKJS_OBJS += quickjs/quickjs-libc.o
QUICKJS_OBJS += quickjs/quickjs.o
QUICKJS_OBJS-$(CONFIG_LIBZMQ) += quickjs/quickjs-zmq.o
QUICKJS_OBJS += $(QUICKJS_OBJS-yes)

$(addprefix $(SUBDIR), quickjs/quickjs-zmq.o): CFLAGS += -I$(SRC_PATH)/libavutil/zeromq/include

QUICKJS_QJS_OBJS += quickjs/qjs.o
QUICKJS_QJS_OBJS += quickjs/qjscalc.o
QUICKJS_QJS_OBJS += quickjs/repl.o
QUICKJS_QJS_OBJS-$(CONFIG_LIBZMQ) += $(ZEROMQ_OBJS)
QUICKJS_QJS_OBJS += $(QUICKJS_QJS_OBJS-yes)

QUICKJS_CONFIG_VERSION := $(shell cat $(SRC_PATH)/libavutil/quickjs/VERSION)

QUICKJS_EXTRA_CFLAGS-$(CONFIG_LIBZMQ) += -DCONFIG_LIBZMQ
QUICKJS_EXTRA_CFLAGS += $(QUICKJS_EXTRA_CFLAGS-yes)
$(addprefix $(SUBDIR), $(QUICKJS_OBJS) $(QUICKJS_QJS_OBJS)): CFLAGS += -D_GNU_SOURCE -DCONFIG_VERSION=\"$(QUICKJS_CONFIG_VERSION)\" -DCONFIG_BIGNUM $(QUICKJS_EXTRA_CFLAGS)

QUICKJS_LIBS=-lm -lpthread
ifneq ($(EXESUF),.exe)
QUICKJS_LIBS+=-ldl
endif

qjs$(EXESUF): $(addprefix $(SUBDIR), $(QUICKJS_OBJS) $(QUICKJS_QJS_OBJS))
	$(CXX) -o $@ $^ $(QUICKJS_LIBS) $(EXTRALIBS-qjs)

OBJS += $(QUICKJS_OBJS)

# sdl2
OBJS-$(CONFIG_SDL2) += quickjs-sdl.o

# Windows resource file
SHLIBOBJS-$(HAVE_GNU_WINDRES)           += avutilres.o

SKIPHEADERS                            += objc.h
SKIPHEADERS-$(HAVE_CUDA_H)             += hwcontext_cuda.h
SKIPHEADERS-$(CONFIG_CUDA)             += hwcontext_cuda_internal.h     \
                                          cuda_check.h
SKIPHEADERS-$(CONFIG_D3D11VA)          += hwcontext_d3d11va.h
SKIPHEADERS-$(CONFIG_D3D12VA)          += hwcontext_d3d12va.h
SKIPHEADERS-$(CONFIG_DXVA2)            += hwcontext_dxva2.h
SKIPHEADERS-$(CONFIG_QSV)              += hwcontext_qsv.h
SKIPHEADERS-$(CONFIG_OPENCL)           += hwcontext_opencl.h
SKIPHEADERS-$(CONFIG_VAAPI)            += hwcontext_vaapi.h
SKIPHEADERS-$(CONFIG_VIDEOTOOLBOX)     += hwcontext_videotoolbox.h
SKIPHEADERS-$(CONFIG_VDPAU)            += hwcontext_vdpau.h
SKIPHEADERS-$(CONFIG_VULKAN)           += hwcontext_vulkan.h vulkan.h   \
                                          vulkan_functions.h            \
                                          vulkan_loader.h

TESTPROGS = adler32                                                     \
            aes                                                         \
            aes_ctr                                                     \
            audio_fifo                                                  \
            avstring                                                    \
            base64                                                      \
            blowfish                                                    \
            bprint                                                      \
            cast5                                                       \
            camellia                                                    \
            channel_layout                                              \
            color_utils                                                 \
            cpu                                                         \
            crc                                                         \
            des                                                         \
            dict                                                        \
            display                                                     \
            encryption_info                                             \
            error                                                       \
            eval                                                        \
            file                                                        \
            fifo                                                        \
            hash                                                        \
            hmac                                                        \
            hwdevice                                                    \
            integer                                                     \
            imgutils                                                    \
            lfg                                                         \
            lls                                                         \
            log                                                         \
            md5                                                         \
            murmur3                                                     \
            opt                                                         \
            pca                                                         \
            parseutils                                                  \
            pixdesc                                                     \
            pixelutils                                                  \
            pixfmt_best                                                 \
            random_seed                                                 \
            rational                                                    \
            ripemd                                                      \
            sha                                                         \
            sha512                                                      \
            side_data_array                                             \
            softfloat                                                   \
            tree                                                        \
            twofish                                                     \
            utf8                                                        \
            uuid                                                        \
            xtea                                                        \
            tea                                                         \

TESTPROGS-$(HAVE_THREADS)            += cpu_init
TESTPROGS-$(HAVE_LZO1X_999_COMPRESS) += lzo

TOOLS = crypto_bench ffhash ffeval ffescape

tools/crypto_bench$(EXESUF): ELIBS += $(if $(VERSUS),$(subst +, -l,+$(VERSUS)),)
tools/crypto_bench.o: CFLAGS += -DUSE_EXT_LIBS=0$(if $(VERSUS),$(subst +,+USE_,+$(VERSUS)),)

$(SUBDIR)tests/lzo$(EXESUF): ELIBS = -llzo2

clean::
	$(RM) $(CLEANSUFFIXES:%=libavutil/quickjs/%) qjs$(EXESUF)
	$(RM) $(CLEANSUFFIXES:%=libavutil/rtmidi/%)
	$(RM) $(CLEANSUFFIXES:%=libavutil/zeromq/external/sha1/%)
	$(RM) $(CLEANSUFFIXES:%=libavutil/zeromq/external/wepoll/%)
	$(RM) $(CLEANSUFFIXES:%=libavutil/zeromq/src/%)

distclean::
	$(RM) libavutil/zeromq/src/platform.hpp
