
include $(SRC_PATH)/tests/ffedit/src/sources.mak

FFEDIT_REF=$(SRC_PATH)/tests/ffedit/ref
FFEDIT_SCRIPTS=$(SRC_PATH)/tests/ffedit/scripts
FFEDIT_JSON=$(SRC_PATH)/tests/ffedit/json

include $(SRC_PATH)/tests/ffedit/mpeg12.mak
include $(SRC_PATH)/tests/ffedit/mjpeg.mak

.PHONY: $(FFEDIT_TESTS)
ffedit-tests: $(FFEDIT_TESTS)
