
include $(SRC_PATH)/tests/ffglitch/src/sources.mak

CAS9_REF=$(SRC_PATH)/tests/ffglitch/ref
CAS9_SCRIPTS=$(SRC_PATH)/tests/ffglitch/scripts
CAS9_JSON=$(SRC_PATH)/tests/ffglitch/json

include $(SRC_PATH)/tests/ffglitch/mpeg12.mak
include $(SRC_PATH)/tests/ffglitch/mjpeg.mak

.PHONY: $(FFGLITCH_TESTS)
ffglitch-tests: $(FFGLITCH_TESTS)
